server:
  port: 8084

spring:
  application:
    name: notification-service

  datasource:
    url: jdbc:postgresql://localhost:5433/notifications_db
    username: admin
    password: admin123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      group-id: notification-service-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: com.ecommerce.notification_service.event.OrderPlacedEvent
        spring.json.use.type.headers: false